name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.5.0+9
  path_provider: ^1.4.0
  camera: ^0.5.7+2
  video_player: ^0.10.0
  image: ^2.0.7
  flutter_bloc: ^0.9.0
  equatable: ^0.2.3
  http: ^0.12.0
  html: ^0.13.4
  scoped_model: ^1.0.1
  flutter_local_notifications: ^0.6.0
  flame: ^0.16.1
  uni_links: ^0.2.0
  amazon_cognito_identity_dart: ^0.0.19
  rxdart: ^0.21.0
  flutter_sound: ^1.4.2
  intl: ^0.16.0
  connectivity: ^0.4.3+5
  palette_generator: ^0.2.0
  percent_indicator: ^2.1.1
  permission_handler: ^3.2.1+1
  location: ^2.3.5
  super_tooltip: ^0.9.0
  sliding_up_panel: ^0.3.6
  device_info: ^0.4.0+4
  draggable_floating_button: ^0.1.1
  tree_view: ^0.0.5
#  sim_info: ^0.1.1
#  sim_service: ^0.1.0
#  app_settings: 1.0.6+2
  photo_manager: ^0.4.3
  flutter_facebook_login: ^3.0.0

  instabug_flutter: ^8.6.4
  provider: ^3.1.0+1

  google_sign_in: ^4.0.14
  firebase_messaging: ^5.1.8

  shared_preferences: ^0.5.4+5

  flutter_kakao_login: ^0.5.0

  flutter_line_sdk: ^1.2.1

  photo_view: ^0.9.0

  sns_wrapper:
    path: ./sns_wrapper

  photofilters: ^1.0.5

  calendar_views: ^0.5.2

  flutter_calendar_carousel: ^1.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# followingge: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/splash_cbbadge_1x.png
   - assets/ic_loading.png
   - assets/line_test.jpg
   - assets/ic_loading_stand.png
   - res/icons/ic_play.png
   - res/icons/ic_stop.png
   - res/icons/ic_pause.png
   - res/icons/ic_mic.png
   - res/icons/ic_volume_down.png
   - res/icons/ic_volume_up.png
   - assets/bg/hinh1.jpg
   - assets/bg/hinh2.jpg
   - assets/bg/hinh3.jpg
   - assets/json/en.json
   - assets/images/vietnam.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
